cloud:
 aws:
   credentials:
     access-key: ""
     secret-key: ""
     
   region:
     static: ap-south-1
     
   stack:
     auto: false
     
appilication:
  bucket:
    name: communication-scaffold/scaffold-chat-data
   
   