# AWS S3 configuration
cloud:
 aws:
   credentials:
     access-key: "AKIA2WBRMZFKJJZ4LRIU"
     secret-key: 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
     
   region:
     static: ap-south-1
          
   bucket:
    name: communication-scaffold/scaffold-chat-data
   
   